on: [push]

jobs:
  fetch_static_secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: Fetch some static secrets
    steps:
      - name: Fetch static secrets from AKeyless
        id: fetch-static-secrets
        uses: cmancone/akeyless-action@main
        with:
          access-id: p-jiu4ebrbyalq
          static-secrets: '{"/MyFirstSecret":"my_first_secret"}'
          export-secrets-to-outputs: true
          export-secrets-to-environment: true
      - name: Output your secret
        run: echo "Your secret is ${{ steps.fetch-static-secrets.outputs.my_first_secret }}"
